
	(function(){function o(){if(!i){i=true;if(s){for(var e=0;e<s.length;e++){s[e].call(window,[])}s=[]}}}function u(e){var t=window.onload;if(typeof window.onload!="function"){window.onload=e}else{window.onload=function(){if(t){t()}e()}}}function a(){if(r){return}r=true;if(document.addEventListener&&!n.opera){document.addEventListener("DOMContentLoaded",o,false)}if(n.msie&&window==top)(function(){if(i)return;try{document.documentElement.doScroll("left")}catch(e){setTimeout(arguments.callee,0);return}o()})();if(n.opera){document.addEventListener("DOMContentLoaded",function(){if(i)return;for(var e=0;e<document.styleSheets.length;e++)if(document.styleSheets[e].disabled){setTimeout(arguments.callee,0);return}o()},false)}if(n.safari){var e;(function(){if(i)return;if(document.readyState!="loaded"&&document.readyState!="complete"){setTimeout(arguments.callee,0);return}if(e===undefined){var t=document.getElementsByTagName("link");for(var n=0;n<t.length;n++){if(t[n].getAttribute("rel")=="stylesheet"){e++}}var r=document.getElementsByTagName("style");e+=r.length}if(document.styleSheets.length!=e){setTimeout(arguments.callee,0);return}o()})()}u(o)}var e=window.DomReady={};var t=navigator.userAgent.toLowerCase();var n={version:(t.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[])[1],safari:/webkit/.test(t),opera:/opera/.test(t),msie:/msie/.test(t)&&!/opera/.test(t),mozilla:/mozilla/.test(t)&&!/(compatible|webkit)/.test(t)};var r=false;var i=false;var s=[];e.ready=function(e,t){a();if(i){e.call(window,[])}else{s.push(function(){return e.call(window,[])})}};a()})()

	if(typeof jQuery=='function'){if(document.doctype&&document.doctype.publicId==""){window.globalLang=window.globalLang||jQuery('html').attr('lang');}else{var userLanguage=(navigator.userLanguage)?navigator.userLanguage.substr(0,2):navigator.language;window.globalLang=window.globalLang||userLanguage}}
DomReady.ready(function(){let dataLayer;if(window.showNumberDataLayerName){dataLayer=window[window.showNumberDataLayerName];}else{dataLayer=window.dataLayer;}
let label='pokaż numer';if(window.globalLang){if(window.globalLang.indexOf('pl')!==-1||window.globalLang.indexOf('szl')!==-1){label='pokaż numer';}else if(window.globalLang.indexOf('de')!==-1){label='Nummer anzeigen';}else if(window.globalLang.indexOf('ru')!==-1){label='показать тел';}else if(window.globalLang.indexOf('fr')!==-1){label='montrer le numéro';}else if(window.globalLang.indexOf('it')!==-1){label='mostra numero';}else if(window.globalLang.indexOf('sk')!==-1){label='zobraziť číslo';}else if(window.globalLang.indexOf('cs')!==-1||window.globalLang.indexOf('cz')!==-1){label='zobrazit číslo';}else{label='show number';}}
if(window.showNumberLabel){label=window.showNumberLabel;}
const linkData=new WeakMap();function revealNumber(link){const data=linkData.get(link);if(!data)return;link.dispatchEvent(new CustomEvent('before-reveal'));data.elementToChange.innerHTML=data.number;const updatedData={...data,numberHidden:false};linkData.set(link,updatedData);link.dispatchEvent(new CustomEvent('after-reveal'));}
const telLinks=document.querySelectorAll('a[href^=tel]');const mobile=/Android.+mobile|webOS|iPhone|iPod|BlackBerry|IEMobile/i.test(navigator.userAgent);telLinks.forEach(function(link){let elementToChange=link;const customClass=link.getAttribute('data-custom-class');if(customClass){const customElement=link.querySelector('.'+customClass);if(customElement){elementToChange=customElement;}}
const number=link.getAttribute('data-number')||elementToChange.textContent;const cutoff=link.getAttribute('data-cutoff')||3;linkData.set(link,{elementToChange:elementToChange,number:number,numberHidden:!mobile});if(link.getAttribute('data-omit')==='true'){return;}
if(!mobile){if(link.hasAttribute('data-number')){const span=document.createElement('span');span.className='show-number';span.innerHTML=elementToChange.innerHTML;elementToChange.innerHTML='';elementToChange.appendChild(span);}else{elementToChange.innerHTML=number.substr(0,cutoff)+'&nbsp;<span class="show-number">'+label+'</span>';}}
link.addEventListener('click',function(e){const data=linkData.get(link);if(!data)return;if(data.numberHidden){e.preventDefault();}
if(typeof dataLayer!=='undefined'&&(mobile||data.numberHidden)){dataLayer.push({'event':'phone conversion','event action':(mobile)?'Kliknięcie numeru na telefonie':'Kliknięcie w "'+label+'"','event label':data.number});}
if(!link.hasAttribute('data-dont-reveal-others')){document.querySelectorAll('a[href^=tel] .show-number').forEach(function(showNumberSpan){const parentLink=showNumberSpan.closest('a');if(parentLink&&!parentLink.hasAttribute('data-dont-reveal-others')){revealNumber(parentLink);}});}else{revealNumber(link);}});});});
